{
 "title": "Hello World",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values({__name__=~\"http_requests_total\"}, instance)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values({__name__=~\"http_requests_total\"}, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "http requests / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"$job\",instance=\"$instance\"}[5m])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "http responce time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "http_responce_time_sum{instance=\"$instance\",job=\"$job\"} / 1000",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Resident memory, mb",
   "type": "timeseries",
   "description": "The actual memory that is used within the virtual memory",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\",job=\"$job\"}/1000000",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "User and system CPU time spent in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"$job\",instance=\"$instance\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}